### ISSUE TITLE
install.sh: rbenv_install_ruby: Ruby openssl extension was not compiled

### ISSUE THREAD

**Issue by 0xmachos** [AbertayHackers/BeEF#3]
Installing Ruby `2.3.0` with `rbenv` (`rbenv install 2.3.0`) fails due to `openssl` extension not being compiled.
```
[INFO] Installing Ruby 2.3.0 via rbenv
Downloading ruby-2.3.0.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.0.tar.bz2
Installing ruby-2.3.0...

BUILD FAILED (Debian 9.4 using ruby-build 20180224)

Inspect or clean up the working tree at /tmp/ruby-build.20180310212506.81358
Results logged to /tmp/ruby-build.20180310212506.81358.log

Last 10 log lines:
installing rdoc:              /home/machos/.rbenv/versions/2.3.0/share/ri/2.3.0/system
installing capi-docs:         /home/machos/.rbenv/versions/2.3.0/share/doc/ruby
The Ruby openssl extension was not compiled.
ERROR: Ruby install aborted due to missing extensions
Try running `apt-get install -y libssl-dev` to fetch missing dependencies.

Configure options used:
  --prefix=/home/machos/.rbenv/versions/2.3.0
  LDFLAGS=-L/home/machos/.rbenv/versions/2.3.0/lib 
  CPPFLAGS=-I/home/machos/.rbenv/versions/2.3.0/include 
[FATAL] Failed to install Ruby 2.3.0 via rbenv
```

 Error message suggests installing `libssl-dev` but it's already installed. 

```
machos@GLaDOS:~/Desktop$ sudo apt install libssl-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libssl-dev is already the newest version (1.1.0f-3+deb9u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

Related issues: 
- https://github.com/rbenv/ruby-build/issues/377
- https://github.com/rbenv/ruby-build/issues/197

**Comment by ecnelises** [comment]
Also have this problem when installing ruby 2.3.5 on Debian 9.4.0.

**Comment by timmc-bcov** [comment]
Possibly related: https://github.com/rbenv/ruby-build/issues/1199

> Ruby < 2.4 is not compatible with openssl 1.1.
> You need to install libssl1.0-dev.

**Comment by 0xmachos** [comment]
@timmc-bcov thanks for pointing us at that issue. 

```
The openssl extension of Ruby version before 2.4 is not compatible with OpenSSL 1.1.x. At the moment, most Linux distributions that come with OpenSSL 1.1.0 have a separate package for OpenSSL 1.0.x.

On Debian 9 (stretch), it is libssl1.0-dev (note installing this would remove libssl-dev).
```
Per [`ruby-build` wiki](https://github.com/rbenv/ruby-build/wiki#openssl-usrincludeopensslasn1_mach102-error-error-this-file-is-obsolete-please-update-your-software).

Changing [line 88](https://github.com/AbertayHackers/BeEF/blob/master/install#L88) of [`install`](https://github.com/AbertayHackers/BeEF/blob/master/install) from `libssl-dev` to `libssl1.0-dev` should fix this.

**Comment by 0xmachos** [comment]
Tested d988eb7cfd73023737f4303678577f88abeb60a2, it works.
